name: Code Review with Checkstyle
on:
  push:
    branches:
      - add-ci
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          reporter: github-pr-review
          level: warning
          checkstyle_config: checkstyle.xml