name: Spotless Check

on:
  pull_request:
    paths:
      - '**/*.java' # Trigger die Pipeline nur wenn Java-Dateien geaendert werden

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17 and Maven
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '17'
    
    - name: Fetch branches
      run: git fetch

    - name: Build and Run Spotless Check
      run: |
        cd video-portal-backend
        mvn clean install
        mvn spotless:check
